mi_vacuum_cleaner:
  host: 你获取的IP
  token: 你获取的Token

sensor:
  - platform: template
    sensors:
      mi_vacuum_cleaner_filter_left:
        unit_of_measurement: '小时'
        icon_template: mdi:clock-outline
        value_template: >-
          {% if state_attr('vacuum.xiaomi_vacuum_cleaner', 'filter_left') < 0 %}
            0
          {% else %}
            {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'filter_left') }}
          {% endif %}
      mi_vacuum_cleaner_side_brush_left:
        unit_of_measurement: '小时'
        icon_template: mdi:clock-outline
        value_template: >-
          {% if state_attr('vacuum.xiaomi_vacuum_cleaner', 'side_brush_left') < 0 %}
            0
          {% else %}
            {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'side_brush_left') }}
          {% endif %}
      mi_vacuum_cleaner_main_brush_left:
        unit_of_measurement: '小时'
        icon_template: mdi:clock-outline
        value_template: >-
          {% if state_attr('vacuum.xiaomi_vacuum_cleaner', 'main_brush_left') < 0 %}
            0
          {% else %}
            {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'main_brush_left') }}
          {% endif %}
      mi_vacuum_cleaner_sensor_dirty_left:
        unit_of_measurement: '小时'
        icon_template: mdi:clock-outline
        value_template: >-
          {% if state_attr('vacuum.xiaomi_vacuum_cleaner', 'sensor_dirty_left') < 0 %}
            0
          {% else %}
            {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'sensor_dirty_left') }}
          {% endif %}
      mi_vacuum_cleaner_cleaning_count:
        unit_of_measurement: '次'
        icon_template: mdi:robot-vacuum
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaning_count') }}"
      mi_vacuum_cleaner_total_cleaning_time:
        unit_of_measurement: '小时'
        icon_template: mdi:clock-outline
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'total_cleaning_time') // 60 }}"
      mi_vacuum_cleaner_total_cleaned_area:
        unit_of_measurement: '平米'
        icon_template: mdi:floor-plan
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'total_cleaned_area') }}"
      mi_vacuum_cleaner_status:
				icon_template: mdi:battery-charging
        value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'status') }}"